### ISSUE TITLE
2 - Launch app when chrome starts in background

### ISSUE THREAD

**Issue by onlykey** [onlykey/OnlyKey-Chrome-App#14]
We need the app to start in the background or at least the settime because without this Google Auth will not work unless the app is started manually. I think the app can be started based on onstartup event it is listening for.

**Comment by jaroszke** [comment]
I think this can be done using background in the permission section in the manifest file. Rod thoughts?

**Comment by rodgolpe** [comment]
Well, [we now have a code branch](https://github.com/onlykey/OnlyKey-Chrome-App/tree/autostart) in which the app loads in the background and sets the OK time without error. There's one *tiny* side-effect, however:  the entire front-end of the app does not work, not even when explicitly loaded. 👎 

Also, I have doubts whether Google will let us publish the app this way. All evidence I've found indicate that the "background" permission we want is only available for hosted apps, legacy packaged apps and extensions, not for Chrome apps. (And we can't switch it to an extension since extensions do not have access to Chrome's USB API.)

This type of background permission was removed from Chrome apps quite a while ago in favor of "system tray support" that ALSO failed to gain traction: https://bugs.chromium.org/p/chromium/issues/detail?id=163770

I've tried the Chrome extension "App Autostart" (Mac and Linux) and it's broken. It tries and fails to auto-launch *itself* in a separate window and never launches my other apps.

The best solution unless/until I really figure otherwise is for users to click the [Apps] ![image](https://cloud.githubusercontent.com/assets/601129/16826971/fec0aed4-494f-11e6-9669-9261a11d535e.png) button in the Chrome bookmarks bar, or to add the OK app directly to their bookmarks bar.

**Comment by onlykey** [comment]
From what I was reading yes background permission is no longer supported but this is because there are other ways to do what we want like event trigger. Launching the app in background to set the time an not launching the front end is what we want but then when explicitly loaded the front end should come up.

**Comment by onlykey** [comment]
So I think you can use this - https://developer.chrome.com/apps/runtime#event-onStartup

If not we can create an extension that sends a message and we start the app when message is received. https://developer.chrome.com/apps/runtime#event-onMessage

**Comment by onlykey** [comment]
@rodgolpe

**Comment by onlykey** [comment]
@rodgolpe I think the way to implement is to put the settime portion of code into and event page https://developer.chrome.com/apps/event_pages Then you don't have to start the whole app. Once the app (with front end) is started you could have the event page stop. What do you think?

**Comment by onlykey** [comment]
I think it would be nice if the event page listened for HID message "INITIALIZED" and triggers when it gets this, then sends set time, then goes inactive.

**Comment by rodgolpe** [comment]
Even if `onStartup` works, we're not listening for "INITIALIZED" -- we're listening for a device connection (which may never occur) and THEN for the initialized message. Not sure that type of listener will even persist. But let's say it does, and we get the initialized message, set the time, and the eventPage goes inactive. If the user unplugs the OK after logging into a site, the eventPage is no longer listening for the next device connection. Furthermore, just exiting Chrome is not enough -- the user will have to open the Chrome Task Manager and shut down all Chrome processes or our eventPage will not receive another `onStartup` message.

**Comment by rodgolpe** [comment]
I stand corrected! The "onDeviceAdded" listener DOES persist after the event page goes to sleep. We're in business. This was added to the [OnlyKey Chrome App beta](https://github.com/onlykey/OnlyKey-Chrome-App/releases/tag/v0.1-beta.0).
