### ISSUE TITLE
Pin steps for Lock, Self-Destruct, PD 

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Chrome-App#15]
If recieving an error whether its too little or to many characters, or pins don't match, have the app stay on the correct step for users to re enter. Rod you will want to confirm with Tim that after a user confirms with a bad pin that the firmware is still looking for a confirmed pin and not starting over.

**Comment by onlykey** [comment]
After a pin does not match or not 7-10 chars the pin set function in firmware goes back to not setting a pin until it receives the setpin message. The process is that when step 3 page on the app begins a setpin message is received to start the set pin process, when next in the app is pressed the OK actually receives two setpin messages. One when exiting step 3 and one when beginning step 4. The setpin message received when step 3 ends tells the OK the user is done with entering a PIN then the PIN is checked for length. If it is not 7-10 characters the OK sends error message and exits set pin function. But then when it receives the setpin message from step 4 it starts it again because it receives another setpin message. We need the error checking function to check for an error message received after the user clicks next on step 3 but before the step 4 sends a setpin message if that makes sense. If it receives an error it should go back to step 3 where it would send a setpin message when step 3 begins. Same thing should be done for checking if the pins match the app should listen for an error message after the user clicks next and the first setpin message is sent but before starting step 4 where the second setpin message is sent. If it gets an error it should return to step 3. This same thing should be done for SDpin (steps 5-6) and PDpin (steps 7-8)

**Comment by rodgolpe** [comment]
This is working as expected now, except the firmware seems to send "Error PIN is not between 7 - 10 characters" for all PIN errors.

**Comment by onlykey** [comment]
@rodgolpe seems to be working good. I have not been able to replicate what you are saying for firmware seems to send "Error PIN is not between 7 - 10 characters" for all PIN errors.

![image](https://cloud.githubusercontent.com/assets/18121756/17060129/9d9da1c2-4ff6-11e6-8d3d-a4830e4223e8.png)

There are only 2 errors one if PIN does not match, one if it is not 7-10 chars
