### ISSUE TITLE
1 - Chrome app fills up with HID data and displays it as labels

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Chrome-App#16]
Labels have values assigned to them when they weren't set.
Steps that led to issue:

1. Configure Pin
2. Set slot for YubiKey auth with label
3. Set another slot to U2F with label

![image](https://cloud.githubusercontent.com/assets/9595840/16140204/845a53fe-341c-11e6-8604-3c05a3d6d726.png)
![image](https://cloud.githubusercontent.com/assets/9595840/16140209/93c5277e-341c-11e6-907b-863b0c8da1da.png)
![image](https://cloud.githubusercontent.com/assets/9595840/16140214/9f8959ae-341c-11e6-95cc-e6503a45f878.png)

**Comment by jaroszke** [comment]
Maybe stemming from current state of OnlyKey but unable to wipe 2a label. 
![image](https://cloud.githubusercontent.com/assets/9595840/16140536/a4c59088-341f-11e6-8782-8f707a14ab4f.png)

**Comment by onlykey** [comment]
This is due to a bug were the app is picking up data from the device responding to U2F like if you are currently registering U2F on https://demo.yubico.com/u2f?tab=register. This may have something to do with ChromeHID driver I saw very odd behavior when attempting register with the Arduino monitor running and Chrome app open. Things like the OK would stop displaying on the serial monitor, Clicking submit on the app causes labels to fill up with data off of USB buffers, then random data being sent to OnlyKey from the Yubikey site the challenge value all As had to reboot system to fix issue.

**Comment by rodgolpe** [comment]
I cannot duplicate this issue with the current version of the app and US firmware.
Can you @onlykey or @jaroszke ?

**Comment by jaroszke** [comment]
Yes I did happen to come across this again

[labelserialmonitorbug.txt](https://github.com/onlykey/OnlyKey-Chrome-App/files/356445/labelserialmonitorbug.txt)
[labelappconsolebug.txt](https://github.com/onlykey/OnlyKey-Chrome-App/files/356446/labelappconsolebug.txt)

**Comment by onlykey** [comment]
@jaroszke Based on the logs provided yk is set as label 1 u2f set as label 2 and 4a set as label 4. There is nothing out of the ordinary. The reason I believe the issue is happening is the app fills up with so much data while listening and receiving U2F traffic that it causes this issue. To reproduce try letting this run https://demo.yubico.com/u2f?tab=register and register a few times and then get labels. The labels are not actually set and if you just restart the app everything is fine.

**Comment by onlykey** [comment]
![image](https://cloud.githubusercontent.com/assets/18121756/17531047/3e3e4da2-5e48-11e6-8af3-bff7c186002e.png)

**Comment by onlykey** [comment]
Second byte sent by OnlyKey is always | for a label filter by that
